[2025-04-27T14:22:43.817+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestao_chuva_15min.transformar_dados scheduled__2025-04-27T04:15:00+00:00 [queued]>
[2025-04-27T14:22:43.822+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestao_chuva_15min.transformar_dados scheduled__2025-04-27T04:15:00+00:00 [queued]>
[2025-04-27T14:22:43.822+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-27T14:22:43.830+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transformar_dados> on 2025-04-27 04:15:00+00:00
[2025-04-27T14:22:43.833+0000] {standard_task_runner.py:60} INFO - Started process 214 to run task
[2025-04-27T14:22:43.835+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestao_chuva_15min', 'transformar_dados', 'scheduled__2025-04-27T04:15:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/ingestao_chuva_15min.py', '--cfg-path', '/tmp/tmp59yp6t2l']
[2025-04-27T14:22:43.836+0000] {standard_task_runner.py:88} INFO - Job 166: Subtask transformar_dados
[2025-04-27T14:22:43.868+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestao_chuva_15min.transformar_dados scheduled__2025-04-27T04:15:00+00:00 [running]> on host 249c3b085d0b
[2025-04-27T14:22:43.923+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestao_chuva_15min' AIRFLOW_CTX_TASK_ID='transformar_dados' AIRFLOW_CTX_EXECUTION_DATE='2025-04-27T04:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-27T04:15:00+00:00'
[2025-04-27T14:22:43.925+0000] {logging_mixin.py:188} INFO - [clima_pluviometro] ðŸ”µ Processando: data/landing/clima_pluviometro/ano=2025/mes=04/dia=27/hora=14/clima_pluviometro_20250427_142241.json
[2025-04-27T14:22:45.761+0000] {logging_mixin.py:188} INFO - [clima_pluviometro] âœ… Parquet salvo em: data/bronze/clima_pluviometro/ano=2025/mes=04/dia=27/hora=14/clima_pluviometro_20250427_142245.parquet
[2025-04-27T14:22:45.761+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/transform.py", line 56, in transformar_json_para_parquet
    os.remove(caminho_json)
FileNotFoundError: [Errno 2] No such file or directory: 'data/landing/clima_pluviometro/ano=2025/mes=04/dia=27/hora=14/clima_pluviometro_20250427_142241.json'
[2025-04-27T14:22:45.767+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestao_chuva_15min, task_id=transformar_dados, execution_date=20250427T041500, start_date=20250427T142243, end_date=20250427T142245
[2025-04-27T14:22:45.776+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 166 for task transformar_dados ([Errno 2] No such file or directory: 'data/landing/clima_pluviometro/ano=2025/mes=04/dia=27/hora=14/clima_pluviometro_20250427_142241.json'; 214)
[2025-04-27T14:22:45.810+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-27T14:22:45.826+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
