[2025-04-30T13:26:12.124+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: adm_cor_comando_ocorrencias_abertas.extrair_dados_ocorrencias_abertas manual__2025-04-30T13:26:11.364126+00:00 [queued]>
[2025-04-30T13:26:12.129+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: adm_cor_comando_ocorrencias_abertas.extrair_dados_ocorrencias_abertas manual__2025-04-30T13:26:11.364126+00:00 [queued]>
[2025-04-30T13:26:12.129+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-30T13:26:12.138+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extrair_dados_ocorrencias_abertas> on 2025-04-30 13:26:11.364126+00:00
[2025-04-30T13:26:12.141+0000] {standard_task_runner.py:60} INFO - Started process 508 to run task
[2025-04-30T13:26:12.142+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'adm_cor_comando_ocorrencias_abertas', 'extrair_dados_ocorrencias_abertas', 'manual__2025-04-30T13:26:11.364126+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/adm_cor_comando.py', '--cfg-path', '/tmp/tmpzii13hx0']
[2025-04-30T13:26:12.144+0000] {standard_task_runner.py:88} INFO - Job 262: Subtask extrair_dados_ocorrencias_abertas
[2025-04-30T13:26:12.178+0000] {task_command.py:423} INFO - Running <TaskInstance: adm_cor_comando_ocorrencias_abertas.extrair_dados_ocorrencias_abertas manual__2025-04-30T13:26:11.364126+00:00 [running]> on host 81c910e0b178
[2025-04-30T13:26:12.242+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='adm_cor_comando_ocorrencias_abertas' AIRFLOW_CTX_TASK_ID='extrair_dados_ocorrencias_abertas' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T13:26:11.364126+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T13:26:11.364126+00:00'
[2025-04-30T13:26:12.243+0000] {logging_mixin.py:188} INFO - Extraindo dados da URL: https://api.dados.rio/v2/adm_cor_comando/ocorrencias_abertas/
[2025-04-30T13:26:22.557+0000] {logging_mixin.py:188} INFO - [ERRO] Falha na extração: HTTPSConnectionPool(host='api.dados.rio', port=443): Read timed out. (read timeout=10)
[2025-04-30T13:26:22.557+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-30T13:26:22.566+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=adm_cor_comando_ocorrencias_abertas, task_id=extrair_dados_ocorrencias_abertas, execution_date=20250430T132611, start_date=20250430T132612, end_date=20250430T132622
[2025-04-30T13:26:22.589+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-30T13:26:22.608+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
